import { defineWorkflow } from '@ramarivera/omp-workflows';
type Args = { base: string; head?: string }; type Slice = { id: string; paths: string[]; rationale: string }; type Finding = { path: string; line: number; message: string; severity: 'low'|'medium'|'high'|'critical'; actionable: boolean; fingerprint: string }; type Result = { findings: Finding[]; reviewedSlices: number; complete: boolean };
const sliceSchema = { type: 'object' } as const; const findingSchema = { type: 'object' } as const; const reportSchema = { type: 'array', items: findingSchema, maxItems: 30 } as const; const resultSchema = { type: 'object' } as const;
export const workflow = defineWorkflow<Args, Result>({ name: 'changed-file-review', version: 1, args: { type: 'object', properties: { base: { type: 'string', minLength: 1 }, head: { type: 'string', minLength: 1 } }, required: ['base'], additionalProperties: false }, limits: { maxConcurrency: 8, maxAgents: 40, maxOutputTokens: 160_000, maxRuntimeMs: 45 * 60_000 }, async run({ args, agent, parallel, phase }) {
 phase('Map changed areas'); const slices = await agent<Slice[]>('Map changed files into non-overlapping review slices.', { id: 'map-areas', agent: 'scout', model: 'fast', effort: 'medium', toolset: ['repo-read'], isolation: { mode: 'none' }, apply: false, schema: { type: 'array', items: sliceSchema, maxItems: 16 }, schemaMode: 'strict' });
 phase('Review areas in parallel'); const reports = await parallel(slices.map((slice) => () => agent<Finding[]>(`Review ${slice.paths.join(', ')} from ${args.base}${args.head ? ` to ${args.head}` : ''}.`, { id: `review:${slice.id}`, agent: 'reviewer', model: 'review', effort: 'high', toolset: ['repo-read'], isolation: { mode: 'none' }, apply: false, schema: reportSchema, schemaMode: 'strict', input: { slice, base: args.base, head: args.head } })), false);
 phase('Deduplicate and completeness gate'); const result = await agent<Result>('Deduplicate by fingerprint and retain only supported actionable findings; report completeness.', { id: 'verify-findings', agent: 'reviewer', model: 'review', effort: 'high', toolset: ['repo-read'], isolation: { mode: 'none' }, apply: false, schema: resultSchema, schemaMode: 'strict', input: { reports, sliceCount: slices.length } });
 if (!result.complete || result.reviewedSlices !== slices.length) throw new Error('Review completeness gate failed'); return result;
} });
